"""GENERATED — do not edit by hand. Regenerate with scripts/gen_lexicon_data.py.

Controlled-substance INNs from the INCB Yellow List, 64th edition
(List of Narcotic Drugs under International Control, 1961 Single
Convention Schedules I/II/IV). The authoritative substance-name
register for el.narcotic_lexicon Tier B.

  source_pdf      : /media/sansforensics/images/YL_64th_E.pdf
  source_pdf_sha  : cc40c28956796319c539dbbfbfb1b0767eb9bd1d0bb9591c75395aa3748a6005
  pdftotext_sha   : ea3fca74c9f2cc52a609d8b0389c68ce577136db8a7776f5b2368eaf49b75c8d
  generated_utc   : 2026-05-27T19:36:57.436493+00:00

SPECIFIC_INN: designer fentanyl/nitazene analogues + obscure NPS —
  near-zero benign-text incidence, treated as standalone-strong.
COMMON_INN: classic opiates + all other scheduled INNs — appear in
  medical/news text, so co-occurrence gated (never fire alone).
"""
from __future__ import annotations

SPECIFIC_INN: tuple[str, ...] = (
    '2-methyl-ap-237',
    '3-methylfentanyl',
    '3-methylthiofentanyl',
    '4-fluoroisobutyrfentanyl',
    'acetyl-alpha-methylfentanyl',
    'acetylfentanyl',
    'acryloylfentanyl',
    'ah-7921',
    'alpha-methylfentanyl',
    'alpha-methylthiofentanyl',
    'beta-hydroxy-3-methylfentanyl',
    'beta-hydroxyfentanyl',
    'brorphine',
    'butonitazene',
    'butyrfentanyl',
    'carfentanil',
    'clonitazene',
    'crotonylfentanyl',
    'cyclopropylfentanyl',
    'etazene',
    'etonitazene',
    'etonitazepipne',
    'etonitazepyne',
    'furanylfentanyl',
    'isotonitazene',
    'methoxyacetylfentanyl',
    'metonitazene',
    'mppp',
    'mt-45',
    'n-desethyl isotonitazene',
    'n-pyrrolidino metonitazene',
    'n-pyrrolidino protonitazene',
    'ocfentanil',
    'orthofluorofentanyl',
    'parafluorobutyrylfentanyl',
    'pepap',
    'protonitazene',
    'thiofentanyl',
    'u-47700',
    'valerylfentanyl',
)

COMMON_INN: tuple[str, ...] = (
    'acetorphine',
    'acetyldihydrocodeine',
    'acetylmethadol',
    'alfentanil',
    'allylprodine',
    'alphacetylmethadol',
    'alphameprodine',
    'alphamethadol',
    'alphaprodine',
    'anileridine',
    'benzethidine',
    'benzylmorphine',
    'betacetylmethadol',
    'betameprodine',
    'betamethadol',
    'betaprodine',
    'bezitramide',
    'cannabis',
    'cannabis resin',
    'cocaine',
    'codeine',
    'codoxime',
    'desomorphine',
    'dextromoramide',
    'dextropropoxyphene',
    'diampromide',
    'diethylthiambutene',
    'difenoxin',
    'dihydroetorphine',
    'dihydromorphine',
    'dimenoxadol',
    'dimepheptanol',
    'dimethylthiambutene',
    'dioxaphetyl butyrate',
    'diphenoxylate',
    'dipipanone',
    'drotebanol',
    'ecgonine',
    'ethylmethylthiambutene',
    'etorphine',
    'etoxeridine',
    'fentanyl',
    'furethidine',
    'heroin',
    'hydrocodone',
    'hydromorphinol',
    'hydromorphone',
    'hydroxypethidine',
    'isomethadone',
    'ketobemidone',
    'levomethorphan',
    'levomoramide',
    'levophenacylmorphan',
    'levorphanol',
    'metazocine',
    'methadone',
    'methyldesorphine',
    'methyldihydromorphine',
    'metopon',
    'morpheridine',
    'morphine',
    'morphine methobromide',
    'morphine-n-oxide',
    'myrophine',
    'nicomorphine',
    'noracymethadol',
    'norlevorphanol',
    'normethadone',
    'normorphine',
    'norpipanone',
    'opium',
    'oripavine',
    'oxycodone',
    'oxymorphone',
    'pethidine',
    'phenadoxone',
    'phenampromide',
    'phenazocine',
    'phenomorphan',
    'phenoperidine',
    'piminodine',
    'piritramide',
    'proheptazine',
    'properidine',
    'racemethorphan',
    'racemoramide',
    'racemorphan',
    'remifentanil',
    'sufentanil',
    'thebacon',
    'thebaine',
    'tilidine',
    'trimeperidine',
)
