"""Per-case CLAUDE.md generator.

Renders a case-scoped CLAUDE.md into the case directory so subsequent
interactive Claude Code sessions on that directory inherit:
  - case identification (id, intake hashes, evidence kind)
  - what EL already produced (findings, graph, IOCs, STIX, audit log)
  - leading hypothesis + score gap (so the analyst sees EL's view immediately)
  - tool/output routing (matches Protocol SIFT conventions)
  - explicit read-only evidence rule

Mirrors the structure of Protocol SIFT's case-templates/CLAUDE.md so an
analyst familiar with that template feels at home.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from el.schemas.finding import Finding


def render(case_dir: Path, manifest: dict, *,
           investigator: str | None = None,
           final_state: str | None = None,
           leading_hypothesis: str | None = None,
           leading_hypothesis_score: int | None = None,
           ach_ranking: list | None = None,
           findings: list[Finding] | None = None) -> Path:
    case_dir = Path(case_dir)
    out = case_dir / "CLAUDE.md"
    findings = findings or []

    by_conf: dict[str, int] = {"high": 0, "medium": 0, "low": 0, "insufficient": 0}
    by_agent: dict[str, int] = {}
    challenged = passed = unresolved = 0
    for f in findings:
        by_conf[f.confidence] = by_conf.get(f.confidence, 0) + 1
        by_agent[f.agent] = by_agent.get(f.agent, 0) + 1
        if f.red_review.status == "passed":
            passed += 1
        elif f.red_review.status == "challenged":
            challenged += 1
        elif f.red_review.status == "unresolved":
            unresolved += 1

    lines: list[str] = []
    lines.append("# CLAUDE.md")
    lines.append("")
    lines.append("This file provides guidance to Claude Code when working in this case directory. "
                 "Generated by EL — Edmond Locard DFIR orchestrator.")
    lines.append("")
    lines.append(f"_Generated {datetime.now(timezone.utc).isoformat(timespec='seconds')}_")
    lines.append("")

    lines.append("## Case Overview")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("|-------|-------|")
    lines.append(f"| **Case ID** | `{manifest.get('case_id','?')}` |")
    lines.append(f"| **Intake (UTC)** | `{manifest.get('intake_utc','?')}` |")
    lines.append(f"| **Investigator** | `{investigator or 'n/a'}` |")
    lines.append(f"| **Evidence Kind** | `{manifest.get('evidence_kind') or '(unclassified)'}` |")
    lines.append(f"| **Final State** | `{final_state or 'n/a'}` |")
    if leading_hypothesis:
        lines.append(f"| **Leading Hypothesis** | `{leading_hypothesis}` (score `{leading_hypothesis_score}`) |")
    lines.append("")

    lines.append("## Evidence Manifest")
    lines.append("")
    lines.append("**Read-only — do NOT modify evidence files.**")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("|-------|-------|")
    lines.append(f"| Input path | `{manifest.get('input_path','?')}` |")
    lines.append(f"| Size (bytes) | `{manifest.get('input_size_bytes','?')}` |")
    lines.append(f"| SHA-256 | `{manifest.get('input_sha256','?')}` |")
    lines.append(f"| SHA-1 | `{manifest.get('input_sha1','?')}` |")
    lines.append(f"| MD5 | `{manifest.get('input_md5','?')}` |")
    lines.append(f"| Magic (first 16 hex) | `{manifest.get('input_magic','?')}` |")
    lines.append("")

    lines.append("## Output Routing")
    lines.append("")
    lines.append("Per Protocol SIFT convention — write all derived data to:")
    lines.append("")
    lines.append("- `./analysis/` — tool outputs grouped by agent")
    lines.append("- `./exports/` — extracted artifacts (files, dumps, IOC bundles)")
    lines.append("- `./reports/` — final reports and machine bundles")
    lines.append("- `./raw/` — raw working space (caches, intermediate files)")
    lines.append("")

    lines.append("## EL Artifacts in This Case")
    lines.append("")
    lines.append("| Artifact | Path | Purpose |")
    lines.append("|----------|------|---------|")
    lines.append(f"| Findings ledger | `findings.sqlite` | All structured Findings (queryable via sqlite3) |")
    lines.append(f"| Locard graph | `graph.kuzu/` | Per-case Kùzu graph (entities + edges) |")
    lines.append(f"| IOC catalog | `iocs.json` | Indicators extracted from all evidence outputs |")
    lines.append(f"| ACH matrix | `ach_matrix.json` | Hypothesis × finding score matrix |")
    lines.append(f"| State transitions | `transitions.json` | Coordinator state-machine trace |")
    lines.append(f"| Forensic audit log | `analysis/forensic_audit.log` | Append-only event log (Protocol SIFT convention) |")
    lines.append(f"| Human report | `reports/report.md` | Markdown report (exec summary + ranking + IOCs) |")
    lines.append(f"| **Case HTML** | `reports/case.html` | Interactive web report with ACH ranking, findings grid |")
    lines.append(f"| **Executive HTML** | `reports/executive.html` | Non-technical stakeholder summary (web view) |")
    lines.append(f"| **Executive PDF** | `reports/executive.pdf` | Printable executive report |")
    lines.append(f"| Findings JSON | `reports/findings.json` | Machine-readable Findings dump |")
    lines.append(f"| STIX 2.1 bundle | `reports/stix-bundle.json` | MISP-importable IOCs + ATT&CK |")
    lines.append("")

    if by_agent:
        lines.append("## Agents That Ran")
        lines.append("")
        lines.append("| Agent | Findings Emitted |")
        lines.append("|-------|---:|")
        for agent, n in sorted(by_agent.items(), key=lambda x: -x[1]):
            lines.append(f"| `{agent}` | {n} |")
        lines.append("")

    lines.append("## Findings Summary")
    lines.append("")
    lines.append(f"- High: **{by_conf['high']}** · Medium: **{by_conf['medium']}** "
                 f"· Low: **{by_conf['low']}** · Insufficient: **{by_conf['insufficient']}**")
    lines.append(f"- Adversarial review: passed={passed}, challenged={challenged}, unresolved={unresolved}")
    lines.append("")

    if ach_ranking:
        lines.append("## Hypothesis Ranking (top 5)")
        lines.append("")
        lines.append("| Rank | Hypothesis | Score |")
        lines.append("|---:|---|---:|")
        for i, r in enumerate(ach_ranking[:5], 1):
            lines.append(f"| {i} | `{r.hyp_id}` — {r.name} | {r.score} |")
        lines.append("")

    lines.append("## Common Re-Run Commands")
    lines.append("")
    lines.append("```bash")
    lines.append(f"# Re-render the report from the existing ledger")
    lines.append(f"# (no re-investigation; deterministic projection)")
    lines.append(f"cd {case_dir}")
    lines.append(f"el ledger {case_dir}                      # list all findings")
    lines.append(f"el report {case_dir} --html              # regenerate HTML reports")
    lines.append(f"sqlite3 findings.sqlite 'SELECT agent, confidence, claim FROM findings'")
    lines.append(f"jq . iocs.json                              # browse IOC catalog")
    lines.append(f"jq '.ranking' ach_matrix.json               # see hypothesis ranking")
    lines.append(f"tail -f analysis/forensic_audit.log         # follow the case event log")
    lines.append("```")
    lines.append("")

    case_id = manifest.get("case_id", "")
    lines.append("## Web View Access")
    lines.append("")
    lines.append("Case reports are available via the EL web server at:")
    lines.append("")
    lines.append(f"- **Interactive case report**: [http://localhost:8089/{case_id}/reports/case.html](http://localhost:8089/{case_id}/reports/case.html)")
    lines.append(f"- **Executive summary**: [http://localhost:8089/{case_id}/reports/executive.html](http://localhost:8089/{case_id}/reports/executive.html)")
    lines.append(f"- **Case directory**: [http://localhost:8089/{case_id}/](http://localhost:8089/{case_id}/)")
    lines.append(f"- **All cases**: [http://localhost:8089/](http://localhost:8089/)")
    lines.append("")

    lines.append("## Forensic Constraints")
    lines.append("")
    lines.append("- This directory is the case workspace — **never** modify the original evidence at the input path above.")
    lines.append("- All UTC timestamps. Defang nothing in the IOC catalog (it is operator output).")
    lines.append("- If you re-run agents manually (outside `el investigate`), append to the audit log:")
    lines.append("  `echo \"$(date -u +%FT%T%z) [INFO] case=<id> event=manual_action ...\" >> analysis/forensic_audit.log`")
    lines.append("")

    out.write_text("\n".join(lines))
    return out
