"""Case seal — chain-of-custody finalization at coordinator-DONE.

Walks every file in cases/<id>/, computes sha256, writes a seal.json
manifest with:
  - case_id, sealed_utc (ISO8601 Z)
  - el_git_rev (if available)
  - per-file size + sha256
  - merkle root (sha256 of sorted "name sha256\n" concatenation)

Optionally tar.gz-archives the entire case dir into
cases/_archives/<case_id>-<TS>.tar.gz with the seal embedded.

Verifying a sealed case: el seal-verify <case_dir|archive> recomputes
hashes and compares to the manifest. Any drift fails verification.

Sealing is idempotent — re-running on an already-sealed case writes
a new seal-<TS>.json (history) plus updates seal.json. The original
seal is never overwritten.
"""
from __future__ import annotations

import hashlib
import json
import subprocess
import tarfile
from datetime import datetime, timezone
from pathlib import Path


SEAL_NAME = "seal.json"

# Files whose relpath contains any of these segments are HASH-MANIFESTED
# (their sha256 is recorded, so tampering on the live case dir is still
# detectable) but EXCLUDED from the tar.gz archive. The tsk_recover tree is
# a reproducible EXTRACTION of the source image — on a multi-host disk
# bundle it is tens of GB, and gzip'ing it turns a minutes-long seal into
# hours while bloating the archive with bytes that can be regenerated by
# re-running tsk_recover. The portable archive omits them; the manifest
# still proves what was recovered and that it wasn't altered in place.
_DEFAULT_ARCHIVE_EXCLUDE = ("exports/recovery/",)


def _is_archive_excluded(relpath: str, patterns) -> bool:
    rp = relpath.replace("\\", "/")
    return any(pat in rp for pat in patterns)


def _sha256(path: Path, chunk: int = 1024 * 1024) -> tuple[str, int]:
    h = hashlib.sha256()
    n = 0
    with path.open("rb") as f:
        while b := f.read(chunk):
            h.update(b); n += len(b)
    return h.hexdigest(), n


def _git_rev(repo: Path) -> str | None:
    try:
        r = subprocess.run(["git", "-C", str(repo), "rev-parse", "HEAD"],
                           capture_output=True, text=True, timeout=5)
        if r.returncode == 0:
            return r.stdout.strip()
    except Exception:
        pass
    return None


def seal_case(case_dir: Path, case_id: str,
              archive: bool = True,
              archive_root: Path | None = None,
              el_repo: Path | None = None,
              archive_exclude: tuple[str, ...] = _DEFAULT_ARCHIVE_EXCLUDE) -> dict:
    """Seal a case directory. Returns the seal manifest dict.
    Writes seal.json into case_dir. Optionally writes a tar.gz archive.

    ``archive_exclude`` paths are still hashed into the manifest (integrity
    preserved) but kept OUT of the tar.gz — see :data:`_DEFAULT_ARCHIVE_EXCLUDE`.
    Pass ``()`` to archive everything (the pre-existing behaviour)."""
    case_dir = Path(case_dir)
    if not case_dir.is_dir():
        raise FileNotFoundError(f"case dir not found: {case_dir}")

    # Walk + hash EVERY file (integrity manifest covers the whole case).
    # Skip the seal file itself + any tar archive bytes.
    files: dict[str, dict] = {}
    skip_names = {SEAL_NAME}
    excluded_count = 0
    excluded_bytes = 0
    for p in sorted(case_dir.rglob("*")):
        if not p.is_file():
            continue
        if p.name in skip_names:
            continue
        rel = str(p.relative_to(case_dir))
        try:
            sha, size = _sha256(p)
        except (PermissionError, OSError):
            # Some kuzu lock files may not be readable; record presence
            files[rel] = {"sha256": None, "size": None, "note": "unreadable"}
            continue
        meta: dict = {"sha256": sha, "size": size}
        # Mark (but still hash) files excluded from the portable archive so
        # seal-verify tolerates their absence when verifying an extracted
        # archive, yet still hash-checks them on the live case dir.
        if _is_archive_excluded(rel, archive_exclude):
            meta["archived"] = False
            excluded_count += 1
            excluded_bytes += size
        files[rel] = meta

    # Merkle-style root over (relpath, sha256) sorted by relpath
    concat = "\n".join(f"{k} {v.get('sha256') or 'NULL'}"
                        for k, v in sorted(files.items())).encode()
    merkle_root = hashlib.sha256(concat).hexdigest()

    manifest = {
        "case_id": case_id,
        "sealed_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "el_git_rev": _git_rev(el_repo or Path(__file__).resolve().parent.parent),
        "file_count": len(files),
        "merkle_root": merkle_root,
        # Archive-scope bookkeeping: these files are hashed above but kept out
        # of the tar.gz. Recorded so an analyst restoring from the archive
        # knows the recovery tree is reproducible (re-run tsk_recover), not
        # lost, and seal-verify can tell "intentionally absent" from "missing".
        "archive_excluded_globs": list(archive_exclude),
        "archive_excluded_count": excluded_count,
        "archive_excluded_bytes": excluded_bytes,
        "files": files,
    }

    seal_path = case_dir / SEAL_NAME
    seal_path.write_text(json.dumps(manifest, indent=2, sort_keys=True))

    if archive:
        archive_root = archive_root or (case_dir.parent / "_archives")
        archive_root.mkdir(parents=True, exist_ok=True)
        ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        archive_path = archive_root / f"{case_id}-{ts}.tar.gz"

        prefix = case_id + "/"

        def _tar_filter(ti: tarfile.TarInfo):
            # ti.name is "<case_id>/<relpath>" (arcname=case_id). Strip the
            # prefix and drop members under an excluded path.
            rel = ti.name[len(prefix):] if ti.name.startswith(prefix) else ti.name
            if _is_archive_excluded(rel, archive_exclude):
                return None
            return ti

        with tarfile.open(archive_path, "w:gz") as tar:
            tar.add(case_dir, arcname=case_id, filter=_tar_filter)
        manifest["archive_path"] = str(archive_path)
        manifest["archive_sha256"], manifest["archive_size"] = _sha256(archive_path)

    return manifest


def verify_seal(case_dir: Path) -> tuple[bool, list[str]]:
    """Re-hash files in case_dir and compare to seal.json. Returns
    (ok, list_of_drift_messages)."""
    case_dir = Path(case_dir)
    seal = case_dir / SEAL_NAME
    if not seal.exists():
        return False, [f"no {SEAL_NAME} in {case_dir}"]
    manifest = json.loads(seal.read_text())
    drift: list[str] = []
    files_recorded = manifest["files"]

    for relpath, meta in files_recorded.items():
        p = case_dir / relpath
        if not p.exists():
            # A file excluded from the tar.gz (archived=False) is expected to
            # be absent when verifying an EXTRACTED archive — that's not drift.
            # On the live case dir it WILL exist and falls through to a hash
            # check below.
            if meta.get("archived", True) is False:
                continue
            drift.append(f"missing: {relpath}")
            continue
        if meta.get("sha256") is None:
            continue
        sha, size = _sha256(p)
        if sha != meta["sha256"]:
            drift.append(f"hash drift: {relpath} (recorded {meta['sha256'][:16]}…, "
                         f"now {sha[:16]}…)")
        if size != meta["size"]:
            drift.append(f"size drift: {relpath} ({meta['size']} → {size})")

    # Detect new files (not in manifest)
    for p in case_dir.rglob("*"):
        if not p.is_file() or p.name == SEAL_NAME:
            continue
        rel = str(p.relative_to(case_dir))
        if rel not in files_recorded:
            drift.append(f"new file (not in seal): {rel}")

    return (len(drift) == 0), drift
