"""AI-generated executive brief for the non-expert report tier.

The deterministic projection (synthesize_executive in narrative.py)
produces a structurally correct digest, but on real cases it leaks
analyst-grade tokens — long detector claims get truncated mid-word,
beat sentences quote raw findings prose, and even with the glossary
the reader can tell it was machine-templated.

For the executive HTML/PDF — which is explicitly NOT court-admissible
per the project agreement — an LLM-rendered structured brief is a
better fit for the audience. The analyst report (case.html, report.md)
and all sections AFTER the brief stay deterministic projections of
findings.sqlite; only this single section uses the LLM.

What the LLM produces (schema_version=2):

  An ``ExecutiveBrief`` with six sections, each a markdown blob the
  renderer turns into HTML. The schema is enforced server-side (the
  LLM is asked for strict JSON; we json-load + Pydantic-validate);
  if any single section is missing or empty we throw the whole
  payload away and the deterministic digest renders instead — no
  half-rendered briefs.

  1. ``what_happened``         — 1-2 plain-English paragraphs
  2. ``what_was_taken``        — markdown bullet list of confirmed loss
  3. ``where_it_went``         — markdown table (channel | destination | evidence)
  4. ``when_timeline``         — markdown table (date | window | what)
  5. ``risk_implications``     — numbered list, executive-tier framing
  6. ``confidence_and_limits`` — explicit "what memory cannot prove"

Forensic discipline that survives the LLM hop:
  * The LLM gets only the structured Finding payload (claim, confidence,
    evidence facts) — never the raw evidence files, never the case
    metadata beyond what the operator typed in.
  * Output is JSON-validated. Schema mismatch ⇒ deterministic fallback,
    not silent half-renders.
  * Output is cached at reports/executive_ai_brief.json with a sha256
    cache key over (schema_version, case_id, leading_hypothesis,
    sorted finding_ids) so re-renders are deterministic unless the
    underlying ledger changed or the operator passed
    ``--regenerate-ai-summary``.
  * The renderer that consumes this output stamps a non-removable
    disclaimer banner ABOVE the brief and a per-section AI chip on
    each rendered section so a reader can't mistake the AI prose for
    the deterministic Findings section.

Falls back cleanly when the API key is absent — returns None and
the renderer falls back to the deterministic digest.
"""
from __future__ import annotations

import hashlib
import json
import os
from datetime import datetime, timezone
from pathlib import Path

from pydantic import BaseModel, Field, ValidationError

from el import llm_defer as _llm_defer
from el.case_metadata import CaseMetadata
from el.reporting.narrative import NarrativeReport
from el.schemas.finding import Finding


# ----- Cache + schema constants ---------------------------------------------

# Bumped from 1 → 2 when the contract changed from a single-paragraph
# string to the six-section ExecutiveBrief. Bumping invalidates every
# cache file from the previous schema (different cache key bytes →
# different sha256 → cache miss → re-render under the new schema).
SCHEMA_VERSION = 2

_CACHE_FILENAME = "executive_ai_brief.json"
_LEGACY_CACHE_FILENAME = "executive_ai_summary.md"   # schema_version=1
_REQUEST_FILENAME = "_ai_brief_request.json"
_DEFAULT_MODEL = os.environ.get("EL_AI_SUMMARY_MODEL", "claude-sonnet-4-6")
# When this env var is set ("1"/"true"/"yes") AND ANTHROPIC_API_KEY is
# absent, synthesize_executive_ai writes a request file under
# reports/_ai_brief_request.json instead of returning None silently.
# The Claude Code skill `el-ai-brief` then fulfils the request on
# behalf of the user, writing the response back to the standard
# cache file (executive_ai_brief.json) which the renderer already
# consumes. See .claude/skills/el-ai-brief/SKILL.md.
DEFER_ENV = "EL_AI_BRIEF_DEFER"
# Claude Code sets CLAUDECODE=1 + CLAUDE_CODE_SESSION_ID + AI_AGENT in
# the subprocess environment, regardless of whether the user passed
# --defer-ai-brief. When EL is launched from inside a Claude Code
# session, the executive brief IS being generated by Claude (the
# orchestrating assistant) — just transported via the el-ai-brief
# skill instead of the Anthropic SDK. Treat it as a first-class AI
# path, not a maybe-someday deferral, and auto-emit the request file
# so the operator never has to remember the flag.
CLAUDE_CODE_ENV = "CLAUDECODE"
# Six sections × ~150 words each + JSON envelope overhead. Generous
# slack so a verbose case doesn't truncate mid-table-row.
_MAX_TOKENS = 4000

# Headless Claude Code CLI fulfilment (Path 2.5). A detached/background run
# has no live assistant to fulfil a deferred request, so the request file
# would otherwise sit forever. When the `claude` binary is present we shell
# out to it (`claude -p`, one-shot, uses the operator's Claude Code auth —
# no API key needed) and generate the brief in-process. The gating +
# subprocess plumbing live in el.llm_defer (shared with the combined brief);
# this call-site only adds a brief-specific opt-in env on top of the global.
_HEADLESS_OPT_IN_ENV = "EL_AI_BRIEF_HEADLESS"


# ----- ExecutiveBrief schema ------------------------------------------------

class ExecutiveBrief(BaseModel):
    """Six-section non-expert brief. Every field is markdown the
    renderer turns into HTML. Empty fields are rejected by the
    validator below so a partial brief never reaches the renderer.
    """

    schema_version: int = SCHEMA_VERSION
    what_happened: str = Field(
        description="1-2 plain-English paragraphs explaining what occurred. "
                    "No ATT&CK IDs, no hypothesis tags, no agent names.",
    )
    what_was_taken: str = Field(
        description="Markdown bullet list of confirmed data loss. Each "
                    "bullet names a project / file / artifact and the "
                    "confidence level in plain words.",
    )
    where_it_went: str = Field(
        description="Markdown table with columns: Channel, Destination, "
                    "Evidence. List each transfer destination on its own "
                    "row. Use 'plausible' / 'confirmed' in the Evidence "
                    "column.",
    )
    when_timeline: str = Field(
        description="Markdown table with columns: Date (UTC), Window, "
                    "What. Chronological. Highlight the exfiltration "
                    "window and any concurrent threat-actor activity.",
    )
    risk_implications: str = Field(
        description="Numbered markdown list of executive-tier risk "
                    "implications. Each item ≤ 2 sentences. No DFIR "
                    "jargon.",
    )
    confidence_and_limits: str = Field(
        description="One paragraph explicitly naming what the memory "
                    "image cannot prove and what disk-side artifacts "
                    "would close those gaps.",
    )

    def reject_empty_sections(self) -> None:
        """Raise ValueError if any section field is empty / whitespace.

        Called separately from Pydantic validation so the LLM-side
        validator can produce a single combined error message instead
        of Pydantic's per-field one.
        """
        empty = [name for name, val in self.model_dump(
            exclude={"schema_version"}).items() if not (val or "").strip()]
        if empty:
            raise ValueError(
                f"ExecutiveBrief rejected — empty section(s): "
                f"{', '.join(empty)}"
            )


# ----- LLM payload + prompt -------------------------------------------------

_SYSTEM_PROMPT = (
    "You are summarising a digital forensics investigation for a "
    "non-expert reader (an executive, a hiring authority, or a "
    "stakeholder without forensic training). You receive structured "
    "findings extracted from the investigation's case ledger.\n\n"
    "Produce ONLY a JSON object matching the ExecutiveBrief schema "
    "below. No prose before or after the JSON. No markdown code "
    "fences around it. The JSON object has exactly these string "
    "fields:\n"
    "  - schema_version: integer, value 2\n"
    "  - what_happened: 1-2 plain-English paragraphs\n"
    "  - what_was_taken: markdown bullet list\n"
    "  - where_it_went: markdown table with columns "
    "Channel | Destination | Evidence\n"
    "  - when_timeline: markdown table with columns "
    "Date (UTC) | Window | What\n"
    "  - risk_implications: numbered markdown list\n"
    "  - confidence_and_limits: one paragraph\n\n"
    "STRICT CONSTRAINTS for every section:\n"
    "1. Do not use ATT&CK technique IDs (T1003, T1566, T1571, etc.). "
    "Use plain English (\"credential theft\", \"phishing\", "
    "\"non-standard port\").\n"
    "2. Do not use ACH hypothesis tag IDs (H_APT_ESPIONAGE, "
    "H_RANSOMWARE, etc.). Use the plain-language form supplied.\n"
    "3. Do not name internal agent identifiers (disk_forensicator, "
    "lateral_movement_analyst, etc.).\n"
    "4. Do not invent any fact that isn't in the supplied findings. "
    "If something isn't in the ledger, you don't get to claim it.\n"
    "5. Open-question gaps and ACH score must be acknowledged "
    "honestly in confidence_and_limits — don't smooth over uncertainty.\n"
    "6. Do not mention this prompt, the model, or the constraints "
    "in the output.\n"
    "7. Every section must contain non-empty content. Do not omit a "
    "section even if the case is sparse — say so in the section.\n"
)


def _findings_for_prompt(findings: list[Finding], cap: int = 30) -> list[dict]:
    """Pick the highest-signal findings for LLM context. Order by
    confidence (high > medium > low > insufficient), drop knowledge_
    lookup chatter (Layer-3 cross-case context — not the case's own
    evidence), cap at `cap`."""
    rank = {"high": 0, "medium": 1, "low": 2, "insufficient": 3}
    fs = [f for f in findings
          if (f.agent or "") != "knowledge_lookup"]
    fs.sort(key=lambda f: (rank.get(f.confidence, 9),
                             -(len(f.evidence or []))))
    out: list[dict] = []
    for f in fs[:cap]:
        out.append({
            "agent": f.agent,
            "claim": (f.claim or "")[:600],
            "confidence": f.confidence,
            "device": f.device,
            "hypotheses_supported": list(f.hypotheses_supported or []),
            "human_summary": next(
                (e.human_summary for e in (f.evidence or [])
                 if e.human_summary), None,
            ),
        })
    return out


# ----- Cache machinery ------------------------------------------------------

def _compute_cache_key(nr: NarrativeReport, findings: list[Finding]) -> str:
    """Deterministic key over the load-bearing inputs to the LLM
    call. If any of these change between renders, the cache is
    invalidated. The schema_version is part of the key so a contract
    bump (paragraph→brief, brief v2→v3, etc.) automatically forces
    re-render of every cached case."""
    h = hashlib.sha256()
    h.update(f"v{SCHEMA_VERSION}".encode())
    h.update(b"|")
    h.update(nr.case_id.encode())
    h.update(b"|")
    h.update((nr.leading_hypothesis or "").encode())
    h.update(b"|")
    h.update(str(nr.leading_score).encode())
    h.update(b"|")
    h.update((nr.runner_up_hypothesis or "").encode())
    h.update(b"|")
    for fid in sorted(f.finding_id for f in findings):
        h.update(fid.encode())
        h.update(b"\n")
    return h.hexdigest()


def _read_cache(cache_path: Path) -> tuple[str | None, ExecutiveBrief | None]:
    """Return (cache_key, brief) from an existing cache file, or
    (None, None) if the file is absent / malformed / fails schema
    validation (e.g. schema bump invalidated it)."""
    if not cache_path.exists():
        return None, None
    try:
        payload = json.loads(cache_path.read_text())
    except (OSError, json.JSONDecodeError):
        return None, None
    cache_key = payload.get("__cache_key")
    brief_dict = payload.get("brief")
    if not cache_key or not isinstance(brief_dict, dict):
        return None, None
    try:
        brief = ExecutiveBrief.model_validate(brief_dict)
        brief.reject_empty_sections()
    except (ValidationError, ValueError):
        return None, None
    return cache_key, brief


def _write_cache(cache_path: Path, cache_key: str,
                  brief: ExecutiveBrief, model: str) -> None:
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "__cache_key": cache_key,
        "__model": model,
        "__generated_utc": datetime.now(timezone.utc).isoformat(),
        "brief": brief.model_dump(),
    }
    cache_path.write_text(json.dumps(payload, indent=2))


# Claude Code deferral detection lives in el.llm_defer (single source of
# truth shared with the red-review challenger). These thin wrappers keep
# the existing call sites + the public name `_running_inside_claude_code`
# stable while delegating the actual logic.
def _defer_enabled() -> bool:
    return _llm_defer.defer_enabled(DEFER_ENV)


def _running_inside_claude_code() -> bool:
    return _llm_defer.running_inside_claude_code()


def _claude_code_path_enabled() -> bool:
    """Either the operator explicitly opted into the deferred path
    (EL_AI_BRIEF_DEFER=1 / --defer-ai-brief), or EL was launched from
    inside a Claude Code session. Either way the request file should
    be written — the el-ai-brief skill picks it up and a Claude model
    fulfils it."""
    return _llm_defer.claude_code_path_enabled(DEFER_ENV)


def _write_request_file(reports_dir: Path, cache_key: str,
                          context: dict, output_path: Path) -> Path:
    """Emit the request payload the Claude Code skill consumes.

    The schema is deliberately self-describing — the system prompt
    and the cache key both ride along — so the skill never has to
    import any EL Python code. The skill's contract: produce a
    response file at ``output_path`` whose ``__cache_key`` matches
    ``cache_key``, then delete this request file.
    """
    reports_dir.mkdir(parents=True, exist_ok=True)
    request_path = reports_dir / _REQUEST_FILENAME
    # Record what triggered the request so the skill (and any human
    # reading the file) can tell "Claude Code orchestrated this run"
    # from "operator explicitly deferred for an out-of-band responder".
    if _running_inside_claude_code():
        trigger = "claude_code_session"
        trigger_session = os.environ.get("CLAUDE_CODE_SESSION_ID") or ""
    elif _defer_enabled():
        trigger = "explicit_defer_flag"
        trigger_session = ""
    else:
        trigger = "unknown"
        trigger_session = ""
    payload = {
        "request_version": 1,
        "cache_key": cache_key,
        "schema_version": SCHEMA_VERSION,
        "output_path": str(output_path),
        "model_hint": _DEFAULT_MODEL,
        "trigger": trigger,
        "trigger_session_id": trigger_session,
        "system_prompt": _SYSTEM_PROMPT,
        "context": context,
        "instructions_for_responder": (
            "Generate a JSON object matching the ExecutiveBrief "
            "schema (six string fields plus schema_version). Write "
            "it to `output_path` wrapped in the cache envelope "
            "{__cache_key, __model, __generated_utc, brief}. Then "
            "delete this request file. The `el-ai-brief` skill in "
            ".claude/skills/ has the full procedure."
        ),
        "generated_utc": datetime.now(timezone.utc).isoformat(),
    }
    request_path.write_text(json.dumps(payload, indent=2))
    return request_path


# ----- LLM response parsing -------------------------------------------------

def _strip_codefence(text: str) -> str:
    """Some models still wrap JSON in ```json … ``` despite instructions.
    Trim that without trying to be clever — first/last ``` lines only."""
    s = text.strip()
    if s.startswith("```"):
        # drop the opening fence line + optional language tag
        s = s.split("\n", 1)[1] if "\n" in s else ""
    if s.endswith("```"):
        s = s.rsplit("\n", 1)[0] if "\n" in s else ""
    return s.strip()


def _parse_brief(text: str) -> ExecutiveBrief | None:
    """Return a validated ExecutiveBrief or None on any parse / schema
    failure. Defensive: malformed payloads must not surface to the
    renderer — better the deterministic fallback than a half-rendered
    brief.
    """
    try:
        data = json.loads(_strip_codefence(text))
    except json.JSONDecodeError:
        return None
    if not isinstance(data, dict):
        return None
    try:
        brief = ExecutiveBrief.model_validate(data)
        brief.reject_empty_sections()
    except (ValidationError, ValueError):
        return None
    return brief


# ----- Headless Claude Code CLI fulfilment (Path 2.5) -----------------------

def _should_use_headless_cli() -> bool:
    """Shared gate (el.llm_defer) plus this call-site's brief-specific
    opt-in env. Fires only for runs with no live assistant — detached
    (``EL_DETACHED=1``) or an explicit headless opt-in."""
    return _llm_defer.should_use_headless_cli(_HEADLESS_OPT_IN_ENV)


def _generate_via_claude_cli(
    context: dict, reports_dir: Path, cache_path: Path,
    cache_key: str, case_id: str, model: str | None,
) -> tuple[ExecutiveBrief, dict] | None:
    """Generate the brief headlessly via `claude -p` (no API key, no live
    session). On success writes the cache envelope and returns
    (brief, metadata); returns None on any failure so the caller falls
    back to the request-file deferral — the brief is never lost, only
    transported differently."""
    chosen = model or _DEFAULT_MODEL
    # The CLI has no separate system-prompt channel in -p mode, so fold
    # the system prompt + JSON context into a single stdin payload.
    prompt = (
        _SYSTEM_PROMPT
        + "\n\n--- CASE CONTEXT (JSON) ---\n"
        + json.dumps(context)
        + "\n\nRespond with ONLY the JSON object described above — no "
          "prose, no code fence."
    )
    text, usage = _llm_defer.run_headless_claude(prompt, chosen)
    if text is None:
        return None
    brief = _parse_brief(text)
    if brief is None:
        return None

    in_tok = usage.get("input_tokens")
    out_tok = usage.get("output_tokens")
    try:
        from el.audit import AuditLog
        AuditLog(reports_dir.parent, case_id).info(
            "llm_call", component="executive_ai",
            model=chosen, transport="claude_cli_headless",
            input_tokens=in_tok, output_tokens=out_tok)
    except Exception:
        pass

    _write_cache(cache_path, cache_key, brief, chosen)
    # Self-fulfilment supersedes any deferred request file (e.g. one left
    # by a prior detach before this backend existed) — drop it so the
    # el-ai-brief skill doesn't redundantly re-process a satisfied request.
    stale_request = reports_dir / _REQUEST_FILENAME
    if stale_request.exists():
        try:
            stale_request.unlink()
        except OSError:
            pass
    return brief, {
        "model": chosen,
        "cache": "miss",
        "transport": "claude_cli_headless",
        "cache_key": cache_key,
        "cache_path": str(cache_path),
        "input_tokens": in_tok,
        "output_tokens": out_tok,
    }


# ----- Public entry point ---------------------------------------------------

def synthesize_executive_ai(
    nr: NarrativeReport,
    findings: list[Finding],
    case_dir: Path,
    case_metadata: CaseMetadata | None = None,
    regenerate: bool = False,
    model: str | None = None,
) -> tuple[ExecutiveBrief, dict] | None:
    """Produce a non-expert-grade executive brief. Returns
    (brief, metadata) or None.

    Auth paths, in order of preference:

      1. **Cache hit** — if reports/executive_ai_brief.json already
         carries the matching cache key, return it (skips network + LLM).
         A previous run, OR the Claude Code skill from path 3, may
         have populated it.

      2. **Direct API** — if ``ANTHROPIC_API_KEY`` is set and the
         ``anthropic`` SDK is importable, call the API directly.

      2.5. **Headless Claude Code CLI** — no API key, but the run has no
         live assistant to fulfil a deferred request (a detached run,
         ``EL_DETACHED=1``, or explicit ``EL_AI_BRIEF_HEADLESS=1``) AND
         the ``claude`` binary is installed. EL shells out to
         ``claude -p`` to generate the brief in-process (uses the
         operator's Claude Code auth, no API key) and writes the cache
         directly — so detached runs produce a complete AI brief with no
         manual follow-up. On any failure it falls through to path 3.

      3. **Claude Code skill fulfilment** — if there's no API key but
         EL is running inside a Claude Code session (CLAUDECODE=1,
         set automatically by the Claude Code CLI) OR the caller
         explicitly opted in via ``EL_AI_BRIEF_DEFER`` /
         ``--defer-ai-brief``, write a request file to
         reports/_ai_brief_request.json and return None. The
         ``el-ai-brief`` skill in .claude/skills/ then fulfils it —
         the brief IS generated by Claude (the orchestrating
         assistant), just transported as a file rather than an SDK
         call. The next render picks up the cache hit (path 1).

    Returns None when:
      * No API key AND not running inside Claude Code AND defer flag
        not set
      * anthropic SDK missing (with API key set)
      * The API call fails for any reason
      * The model returns malformed JSON or a brief that fails
        schema validation (any empty section)
    """
    cache_path = Path(case_dir) / "reports" / _CACHE_FILENAME
    reports_dir = cache_path.parent
    desired_key = _compute_cache_key(nr, findings)

    # Path 1: cache check — runs first, regardless of auth posture.
    if not regenerate:
        existing_key, existing_brief = _read_cache(cache_path)
        if existing_key == desired_key and existing_brief is not None:
            return existing_brief, {
                "model": model or _DEFAULT_MODEL,
                "cache": "hit", "cache_key": desired_key,
                "cache_path": str(cache_path),
            }

    # Build context payload once — both the API path and the defer
    # path send the same dict.
    plain_leading = nr.leading_hypothesis or "no leading theory"
    context = {
        "case_id": nr.case_id,
        "leading_hypothesis_plain": plain_leading,
        "leading_hypothesis_score": nr.leading_score,
        "leading_hypothesis_gap": nr.leading_gap,
        "runner_up_hypothesis": nr.runner_up_hypothesis,
        "evidence_time_range": list(nr.evidence_time_range or []),
        "case_metadata": (
            {"objective": case_metadata.objective_statement,
             "investigator": case_metadata.investigator_name}
            if case_metadata and not case_metadata.is_empty() else None
        ),
        "deterministic_digest_sentences": (
            getattr(nr, "deterministic_digest", None) or []
        ),
        "top_findings": _findings_for_prompt(findings),
        "open_questions_count": nr.insufficient_count,
        "open_questions_sample": [
            (f.claim or "")[:200] for f in nr.insufficient_findings[:5]
        ],
    }

    api_key = os.environ.get("ANTHROPIC_API_KEY")

    # Path 3: Claude Code skill fulfilment. Triggered when either
    #   (a) EL is running inside a Claude Code session — detected via
    #       CLAUDECODE / AI_AGENT env vars (the user's orchestrating
    #       assistant IS Claude, so this is not really a "deferral";
    #       the brief gets generated in the same session by the
    #       el-ai-brief skill, just via a file handoff instead of the
    #       Anthropic SDK), OR
    #   (b) the caller opted in explicitly via EL_AI_BRIEF_DEFER /
    #       --defer-ai-brief outside Claude Code (the request file
    #       then sits until some responder fulfils it).
    # In either case the renderer falls back to the deterministic
    # digest on THIS pass; the AI brief lands on the next render once
    # the skill has populated executive_ai_brief.json.
    if not api_key:
        # Path 2.5: a detached/background run (EL_DETACHED=1) propagates
        # CLAUDECODE in its unit env, so it looks like a Claude Code
        # session and would defer — but no live assistant is attached to
        # fulfil the request file. Self-fulfil it headlessly via
        # `claude -p` instead, so detached runs get a complete AI brief
        # with no manual follow-up. On any failure, fall through to the
        # request-file deferral (the brief is transported, never lost).
        if _should_use_headless_cli():
            result = _generate_via_claude_cli(
                context, reports_dir, cache_path, desired_key,
                nr.case_id, model)
            if result is not None:
                return result
        if _claude_code_path_enabled():
            _write_request_file(reports_dir, desired_key, context, cache_path)
        return None

    # Path 2: direct API.
    try:
        import anthropic
    except ImportError:
        return None
    client = anthropic.Anthropic(api_key=api_key)
    chosen = model or _DEFAULT_MODEL
    try:
        msg = client.messages.create(
            model=chosen,
            max_tokens=_MAX_TOKENS,
            system=_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": json.dumps(context)}],
        )
        text = "".join(
            b.text for b in msg.content
            if getattr(b, "type", "") == "text"
        ).strip()
    except Exception:
        return None

    _usage = getattr(msg, "usage", None)
    _in_tok = getattr(_usage, "input_tokens", None)
    _out_tok = getattr(_usage, "output_tokens", None)
    # Token usage → forensic audit log so it surfaces in the execution
    # log alongside every other run event (Find Evil: tool/agent execution
    # logs must include token usage for LLM-backed steps).
    try:
        from el.audit import AuditLog
        AuditLog(reports_dir.parent, nr.case_id).info(
            "llm_call", component="executive_ai", model=chosen,
            input_tokens=_in_tok, output_tokens=_out_tok)
    except Exception:
        pass

    brief = _parse_brief(text)
    if brief is None:
        return None

    _write_cache(cache_path, desired_key, brief, chosen)
    return brief, {
        "model": chosen,
        "cache": "miss",
        "cache_key": desired_key,
        "cache_path": str(cache_path),
        "input_tokens": _in_tok,
        "output_tokens": _out_tok,
    }


# Disclaimer string the renderer is required to display alongside the
# AI brief. Hard-coded here so a renderer change can't drop the
# disclaimer; the test for the disclaimer label imports this constant.
DISCLAIMER_LABEL = (
    "AI-generated executive brief — not court-admissible. The Findings, "
    "Conclusion, and Recommendations sections below are deterministic "
    "projections of the analyst ledger."
)

# Per-section chip text rendered next to each section header so a
# reader scanning a single section still sees the AI provenance.
SECTION_AI_CHIP = "AI-rendered"


__all__ = [
    "synthesize_executive_ai",
    "ExecutiveBrief",
    "SCHEMA_VERSION",
    "DISCLAIMER_LABEL",
    "SECTION_AI_CHIP",
    "DEFER_ENV",
    "_REQUEST_FILENAME",
]
