"""Executive PDF renderer.

Renders `reports/executive.html` to `reports/executive.pdf` via
WeasyPrint. The PDF is the printable / emailable form of the
executive report; the HTML stays for browser preview and as the
source of truth (PDF is a derivative, never authoritative).

Engagement scope (per project agreement): not court-compliant. No
PDF/A, no digital signing, no rasterised page-by-page images. Just
a clean paginated rendering with page numbers and a header so the
stakeholder can print or attach to email.

The PDF is not separately hashed — `seal.py` walks the entire
case dir and includes whatever it finds, so executive.pdf goes
into the merkle root automatically alongside executive.html.

Failure mode: when WeasyPrint isn't importable (system deps missing
on a non-SIFT host), this module raises `WeasyPrintNotAvailable`
with a one-line install hint. The CLI catches that and prints a
yellow warning rather than crashing the whole report run.
"""
from __future__ import annotations

from pathlib import Path


class WeasyPrintNotAvailable(RuntimeError):
    """Raised when weasyprint can't be imported. Distinct exception
    so callers can downgrade to a warning instead of a crash."""


# CSS injected on top of the exec HTML's own stylesheet — adds
# paginated-media rules that only matter when rendering to PDF
# (page numbers, header band, page-break hints). Browser preview
# of executive.html is unaffected because @page rules are inert
# when displayed on screen.
_PDF_CSS = """
@page {
  size: A4;
  margin: 18mm 16mm 22mm 16mm;
  @top-center {
    content: string(case-title);
    font-family: "Helvetica Neue", Arial, sans-serif;
    font-size: 9pt;
    color: #888;
  }
  @bottom-right {
    content: "Page " counter(page) " of " counter(pages);
    font-family: "Helvetica Neue", Arial, sans-serif;
    font-size: 9pt;
    color: #888;
  }
  @bottom-left {
    content: "Executive report — generated by EL";
    font-family: "Helvetica Neue", Arial, sans-serif;
    font-size: 9pt;
    color: #888;
  }
}
@page :first {
  /* No header on the title page — looks cleaner. */
  @top-center { content: ""; }
}
h1 {
  /* Capture the document title once so the running header on every
     subsequent page can echo it. */
  string-set: case-title content();
}
/* Stronger page-break controls than the screen CSS — avoid orphan
   headings, keep recommendations + glossary entries together. */
h2, h3 { page-break-after: avoid; }
.recommendation, .glossary-entry, .summary-box { page-break-inside: avoid; }
table.kv tr { page-break-inside: avoid; }
.finding-row { page-break-inside: avoid; }
"""


def _try_import_weasyprint():
    try:
        import weasyprint  # noqa: F401
        return weasyprint
    except (ImportError, OSError) as e:
        # OSError surfaces when the Python package is installed but
        # the underlying cairo/pango/gdk-pixbuf shared libs aren't
        # present (some minimal containers).
        raise WeasyPrintNotAvailable(
            f"WeasyPrint is not available ({e}). Install with "
            f"`pip install weasyprint` and verify cairo + pango + "
            f"gdk-pixbuf system libraries are present."
        ) from e


def render_executive_pdf(
    executive_html: str | Path,
    output_path: str | Path | None = None,
) -> Path:
    """Render the executive HTML report to a paginated PDF.

    `executive_html` is the path to the HTML file produced by
    `el.reporting.executive.render_executive_html`. The PDF is
    written to `output_path` if supplied, otherwise to
    `reports/executive.pdf` next to the source HTML.

    Returns the output path. Raises `WeasyPrintNotAvailable` when
    WeasyPrint cannot be imported.
    """
    weasyprint = _try_import_weasyprint()

    src = Path(executive_html)
    if not src.exists():
        raise FileNotFoundError(f"executive HTML not found: {src}")

    out = Path(output_path) if output_path else src.with_suffix(".pdf")
    out.parent.mkdir(parents=True, exist_ok=True)

    # base_url so any relative references in the HTML resolve
    # against the case's reports/ directory.
    html_doc = weasyprint.HTML(filename=str(src), base_url=str(src.parent))
    extra_css = weasyprint.CSS(string=_PDF_CSS)
    html_doc.write_pdf(target=str(out), stylesheets=[extra_css])
    return out


__all__ = ["render_executive_pdf", "WeasyPrintNotAvailable"]
